FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:20-alpine AS dev
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0"]

FROM node:20-alpine AS builder
WORKDIR /app
ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_CSRF_SECRET_KEY
ARG NEXT_PUBLIC_PASSWORD_SECRET_KEY
ARG NEXT_PUBLIC_PASSWORD_SECRET_IV
ARG NEXT_PUBLIC_PAYLOAD_ENCRYPTION_KEY
ARG NEXT_PUBLIC_PAYLOAD_ENCRYPTION_IV
ARG NEXT_PUBLIC_DEFAULT_TENANT_UUID
ARG NEXT_PUBLIC_APP_ORIGIN
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_CSRF_SECRET_KEY=$NEXT_PUBLIC_CSRF_SECRET_KEY
ENV NEXT_PUBLIC_PASSWORD_SECRET_KEY=$NEXT_PUBLIC_PASSWORD_SECRET_KEY
ENV NEXT_PUBLIC_PASSWORD_SECRET_IV=$NEXT_PUBLIC_PASSWORD_SECRET_IV
ENV NEXT_PUBLIC_PAYLOAD_ENCRYPTION_KEY=$NEXT_PUBLIC_PAYLOAD_ENCRYPTION_KEY
ENV NEXT_PUBLIC_PAYLOAD_ENCRYPTION_IV=$NEXT_PUBLIC_PAYLOAD_ENCRYPTION_IV
ENV NEXT_PUBLIC_DEFAULT_TENANT_UUID=$NEXT_PUBLIC_DEFAULT_TENANT_UUID
ENV NEXT_PUBLIC_APP_ORIGIN=$NEXT_PUBLIC_APP_ORIGIN
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
COPY --from=builder /app ./
EXPOSE 3000
CMD ["npm", "start"]
