export type SalaryComponentListRecord = {
  intID: number;
  strComponentCode: string;
  strComponentName: string;
  blnIsWages: boolean;
  strComponentCategory: string;
  strComponentGroup: string | null;
  strCalcMethod: string;
  strRoundingRule: string | null;
  strDefaultPeriodicity: string;
  strTaxTreatment: string | null;
  blnIncludeInPF: boolean;
  blnIncludeInESIC: boolean;
  blnIncludeInGratuity: boolean;
  blnIncludeInRemuneration: boolean;
  blnIncludeInTaxableIncome: boolean;
  blnIncludedInCtc: boolean;
  blnIncludeInPayslip: boolean;
  strPayslipSection: string | null;
  intDisplayOrder: number;
  intLwpTreatmentID?: number | null;
  strLwpTreatmentCode?: string | null;
  strLwpTreatment?: string | null;
  intLwpReducedAmountHandlingID?: number | null;
  strLwpReducedAmountHandlingCode?: string | null;
  strLwpReducedAmountHandling?: string | null;
  strLwpProrationFormula?: string | null;
  blnIsReimbursement: boolean;
  blnIsFlexiBenefit: boolean;
  blnIsFlexiBasket?: boolean;
  strFlexiComponentType?: string | null;
  strReimbursementType: string | null;
  strSettlementMethod: string | null;
  blnRequiresBills: boolean;
  blnExpenseDateRequired?: boolean;
  blnAllowPartialApproval?: boolean;
  decAnnualLimitAmount: number | null;
  decMonthlyLimitAmount: number | null;
  strClaimLimitType: string | null;
  blnAllowExcessClaim: boolean;
  blnExcessClaimTaxable: boolean;
  intResidualComponentID: number | null;
  blnAutoPushToPayroll: boolean;
  blnFinanceSettlementRequired: boolean;
  blnIsEmployerContribution: boolean;
  blnIsEmployeeDeduction: boolean;
  blnDeclarationRequired: boolean;
  blnProofRequired: boolean;
  blnAllowManualOverride: boolean;
  blnIsActive: boolean;
  intDependencyCount: number;
};

export type SalaryComponentOption = {
  intID: number;
  strLabel: string;
  strCode?: string;
};

export type SalaryComponentLookupOption = {
  intID: number;
  strValueCode: string;
  strDisplayName: string;
  strDescription: string | null;
  intDisplayOrder: number;
  blnIsActive: boolean;
  strLegacyValue?: string | null;
};

export type SalaryComponentFlexiEligibilityQuestion = {
  intID: number;
  strQuestionCode: string;
  strAnswerType: string;
  strSourceType: string;
  blnIsEmployeeEditable: boolean;
  strDefaultLabel: string;
  strDefaultHelpText: string | null;
  strValueUnit: string | null;
  decMinValue: number | null;
  decMaxValue: number | null;
  objOptionJSON?: unknown;
  intDisplayOrder: number;
  blnIsActive: boolean;
  lstTexts: Array<{
    intLanguageID: number;
    strQuestionLabel: string;
    strHelpText: string | null;
  }>;
};

export type SalaryComponentFlexiEligibilityRuleFormValue = {
  strRowID: string;
  intID?: number;
  intEligibilityQuestionID: number | "";
  strOperator: string;
  strExpectedValue: string;
  strMinValue: string;
  strMaxValue: string;
  strMultiplierMode: string;
  strMultiplierCap: string;
  strIneligibleBehavior: string;
  strFailureMessage: string;
  blnIsRequired: boolean;
  blnIsActive: boolean;
  intDisplayOrder: number;
};

export type SalaryComponentTextFormValue = {
  strRowID: string;
  intLanguageID: number | "";
  strLanguageName: string;
  strComponentName: string;
  strComponentDescription: string;
};

export type SalaryComponentFormValues = {
  strComponentCode: string;
  strComponentName: string;
  strComponentDescription: string;
  blnIsWages: boolean;
  intComponentCategoryID: number | "";
  strComponentCategory: string;
  intComponentGroupID: number | "";
  strComponentGroup: string;
  intCalcMethodID: number | "";
  strCalcMethod: string;
  strFormulaExpression: string;
  strDefaultPercentageValue: string;
  intDefaultBasisComponentID: number | "";
  intRoundingRuleID: number | "";
  strRoundingRule: string;
  intDefaultPeriodicityID: number | "";
  strDefaultPeriodicity: string;
  intTaxTreatmentID: number | "";
  strTaxTreatment: string;
  intCtcTreatmentID: number | "";
  blnIncludeInPF: boolean;
  blnIncludeInESIC: boolean;
  blnIncludeInGratuity: boolean;
  blnIncludeInRemuneration: boolean;
  blnIncludeInTaxableIncome: boolean;
  blnIncludeInPayslip: boolean;
  intPayslipSectionID: number | "";
  strPayslipSection: string;
  strDisplayOrder: string;
  intLwpTreatmentID: number | "";
  strLwpTreatmentCode: string;
  intLwpReducedAmountHandlingID: number | "";
  strLwpReducedAmountHandlingCode: string;
  strLwpProrationFormula: string;
  blnIsFlexiBenefit: boolean;
  blnIsReimbursement: boolean;
  intReimbursementTypeID: number | "";
  strReimbursementType: "none" | "ctc_based" | "non_ctc_based";
  blnIncludedInCtc: boolean;
  intSettlementMethodID: number | "";
  strSettlementMethod: "none" | "payroll" | "finance";
  blnRequiresBills: boolean;
  blnExpenseDateRequired: boolean;
  blnAllowPartialApproval: boolean;
  intApplicableTaxRegimeID: number | "";
  intApplicableForWhichTaxRegime: 0 | 1 | 2;
  intClaimLimitTypeID: number | "";
  strClaimLimitType: "none" | "monthly" | "yearly" | "both";
  intFlexiComponentTypeID: number | "";
  intFlexiBalanceHandlingID: number | "";
  strAnnualLimitAmount: string;
  strMonthlyLimitAmount: string;
  blnAllowExcessClaim: boolean;
  blnExcessClaimTaxable: boolean;
  intResidualComponentID: number | "";
  blnAutoPushToPayroll: boolean;
  blnFinanceSettlementRequired: boolean;
  blnIsEmployerContribution: boolean;
  blnIsEmployeeDeduction: boolean;
  blnDeclarationRequired: boolean;
  blnProofRequired: boolean;
  blnAllowManualOverride: boolean;
  blnIsActive: boolean;
  lstDependencyComponentIDs: number[];
  lstFlexiEligibilityRules: SalaryComponentFlexiEligibilityRuleFormValue[];
  lstTexts: SalaryComponentTextFormValue[];
};

export type SalaryComponentDetailRecord = SalaryComponentListRecord & {
  strComponentDescription: string | null;
  intComponentCategoryID?: number | null;
  intComponentGroupID?: number | null;
  strComponentGroup: string | null;
  intCalcMethodID?: number | null;
  strFormulaExpression: string | null;
  decDefaultPercentageValue?: number | null;
  intDefaultBasisComponentID?: number | null;
  intRoundingRuleID?: number | null;
  strRoundingRule: string | null;
  intDefaultPeriodicityID?: number | null;
  intTaxTreatmentID?: number | null;
  strTaxTreatment: string | null;
  intCtcTreatmentID?: number | null;
  intReimbursementTypeID?: number | null;
  intSettlementMethodID?: number | null;
  intClaimLimitTypeID?: number | null;
  intFlexiComponentTypeID?: number | null;
  intFlexiBalanceHandlingID?: number | null;
  intPayslipSectionID?: number | null;
  intLwpTreatmentID?: number | null;
  strLwpTreatmentCode?: string | null;
  intLwpReducedAmountHandlingID?: number | null;
  strLwpReducedAmountHandlingCode?: string | null;
  strLwpProrationFormula?: string | null;
  intApplicableTaxRegimeID?: number | null;
  intApplicableForWhichTaxRegime?: number | null;
  intUsedInSalaryStructures: number;
  intAssignedEmployees: number;
  intFormulaReferences: number;
  lstDependencyComponentIDs: number[];
  lstFlexiEligibilityRules: Array<{
    intID?: number;
    intEligibilityQuestionID: number;
    strOperator: string;
    strExpectedValue: string | null;
    fltMinValue: number | null;
    fltMaxValue: number | null;
    strMultiplierMode: string;
    fltMultiplierCap: number | null;
    strIneligibleBehavior: string;
    strFailureMessage: string | null;
    blnIsRequired: boolean;
    blnIsActive: boolean;
    intDisplayOrder: number;
    objQuestion?: SalaryComponentFlexiEligibilityQuestion | null;
  }>;
  lstTexts: Array<{
    intLanguageID: number;
    strLanguageName: string;
    strComponentName: string;
    strComponentDescription: string | null;
  }>;
  lstDependencyComponents: Array<{
    intSalaryComponentID: number;
    strComponentCode: string | null;
    strComponentName: string;
  }>;
};

export type SalaryComponentFormOptions = {
  lstLanguages: SalaryComponentOption[];
  lstDependencyComponents: SalaryComponentOption[];
  lstFlexiEligibilityQuestions: SalaryComponentFlexiEligibilityQuestion[];
  lstResidualComponents: SalaryComponentOption[];
  lstComponentCategoryLookups?: SalaryComponentLookupOption[];
  lstComponentCategories: string[];
  lstComponentGroupLookups?: SalaryComponentLookupOption[];
  lstComponentGroups: string[];
  lstCalcMethodLookups?: SalaryComponentLookupOption[];
  lstCalcMethods: string[];
  lstRoundingRuleLookups?: SalaryComponentLookupOption[];
  lstRoundingRules: string[];
  lstDefaultPeriodicityLookups?: SalaryComponentLookupOption[];
  lstDefaultPeriodicities: string[];
  lstTaxTreatmentLookups?: SalaryComponentLookupOption[];
  lstTaxTreatments: string[];
  lstCtcTreatmentLookups?: SalaryComponentLookupOption[];
  lstReimbursementTypeLookups?: SalaryComponentLookupOption[];
  lstReimbursementTypes: string[];
  lstSettlementMethodLookups?: SalaryComponentLookupOption[];
  lstSettlementMethods: string[];
  lstClaimLimitTypeLookups?: SalaryComponentLookupOption[];
  lstClaimLimitTypes: string[];
  lstFlexiComponentTypeLookups?: SalaryComponentLookupOption[];
  lstFlexiBalanceHandlingLookups?: SalaryComponentLookupOption[];
  lstPayslipSectionLookups?: SalaryComponentLookupOption[];
  lstLwpTreatmentLookups?: SalaryComponentLookupOption[];
  lstLwpReducedAmountHandlingLookups?: SalaryComponentLookupOption[];
  lstApplicableTaxRegimeLookups?: SalaryComponentLookupOption[];
};
