"use client";

import { useCallback, useEffect, useRef, useState } from "react";

import type { PayrollJobStatus } from "@/features/payroll/types";

const intKeepOnScreenMilliseconds = 1100;

/**
 * Shows the shared progress dialog while ONE payslip is generated by a single request.
 *
 * The server cannot report partial progress for a single payslip, so the bar eases toward 90%
 * while the request is in flight and jumps to 100% when it succeeds. On failure the dialog is
 * removed at once so the page's own error message is visible. After success the 100% state is
 * left on screen briefly without making the caller wait.
 */
export function usePayslipGenerationProgress(strPhaseLabel = "Generating payslip") {
  const [objPayslipProgress, setObjPayslipProgress] = useState<PayrollJobStatus | null>(null);
  const refTimer = useRef<number | null>(null);
  const refClearTimer = useRef<number | null>(null);

  const stopTimer = useCallback(() => {
    if (refTimer.current !== null) {
      window.clearInterval(refTimer.current);
      refTimer.current = null;
    }
  }, []);

  useEffect(
    () => () => {
      stopTimer();
      if (refClearTimer.current !== null) {
        window.clearTimeout(refClearTimer.current);
      }
    },
    [stopTimer],
  );

  const trackPayslipGeneration = useCallback(
    async <TResult,>(fnWork: () => Promise<TResult>): Promise<TResult> => {
      stopTimer();
      if (refClearTimer.current !== null) {
        window.clearTimeout(refClearTimer.current);
        refClearTimer.current = null;
      }
      let fltPercent = 4;
      const fnBuild = (strStatus: PayrollJobStatus["strStatus"], intPercent: number): PayrollJobStatus => ({
        strStatus,
        blnActive: strStatus === "running",
        strKind: "payslips",
        strPhase: "generating",
        strPhaseLabel,
        intPercent,
      });
      setObjPayslipProgress(fnBuild("running", fltPercent));
      refTimer.current = window.setInterval(() => {
        fltPercent += (90 - fltPercent) * 0.12;
        setObjPayslipProgress(fnBuild("running", Math.round(fltPercent)));
      }, 150);
      try {
        const objResult = await fnWork();
        stopTimer();
        setObjPayslipProgress(fnBuild("completed", 100));
        refClearTimer.current = window.setTimeout(() => setObjPayslipProgress(null), intKeepOnScreenMilliseconds);
        return objResult;
      } catch (objError) {
        stopTimer();
        setObjPayslipProgress(null);
        throw objError;
      }
    },
    [stopTimer, strPhaseLabel],
  );

  return { objPayslipProgress, trackPayslipGeneration };
}
