const dicModuleAliases: Record<string, string> = {
  "common-data-grid": "common",
  "common_data_grid": "common",
  "employee-payroll-input": "employee-payroll-input",
  "employee-payroll-inputs": "employee-payroll-input",
  employee_payroll_input: "employee-payroll-input",
  employee_payroll_inputs: "employee-payroll-input",
  payslip: "payslips",
  payslips: "payslips",
  "my-payslip": "payslips",
  "my-payslips": "payslips",
  "ess-payslip": "payslips",
  "ess-payslips": "payslips",
  "payroll-payslip": "payslips",
  "payroll-payslips": "payslips",
  my_payslip: "payslips",
  my_payslips: "payslips",
  ess_payslip: "payslips",
  ess_payslips: "payslips",
  payroll_payslip: "payslips",
  payroll_payslips: "payslips",
  "payroll-result": "payroll-results",
  "payroll-results": "payroll-results",
  payroll_result: "payroll-results",
  payroll_results: "payroll-results",
  "payroll-run": "payroll-cycles",
  "payroll-runs": "payroll-cycles",
  payroll_run: "payroll-cycles",
  payroll_runs: "payroll-cycles",
  "payroll-process-log": "payroll-process-logs",
  "payroll-process-logs": "payroll-process-logs",
  payroll_process_log: "payroll-process-logs",
  payroll_process_logs: "payroll-process-logs",
  "tax-declaration-component": "tax-declaration-components",
  "tax-declaration-components": "tax-declaration-components",
  tax_declaration_component: "tax-declaration-components",
  tax_declaration_components: "tax-declaration-components",
  "ess-declaration-category": "tax-declaration-components",
  "ess-declaration-categories": "tax-declaration-components",
  ess_declaration_category: "tax-declaration-components",
  ess_declaration_categories: "tax-declaration-components",
  "ess-loan-advance": "loans-advances",
  "ess-loans-advances": "loans-advances",
  "loan-advance": "loans-advances",
  "loan-advances": "loans-advances",
  "loans-advance": "loans-advances",
  "loans-advances": "loans-advances",
  loans_advances: "loans-advances",
  "payroll-loans-advances": "loans-advances",
  payroll_loans_advances: "loans-advances",
};

export function normalizeLabelModuleName(strModuleName: string) {
  const strNormalized = strModuleName.trim().toLowerCase();
  return dicModuleAliases[strNormalized] ?? strNormalized;
}
