export enum ApiRequestMethod {
  Get = "GET",
  Post = "POST",
  Put = "PUT",
  Delete = "DELETE",
}

export enum ApiResultCode {
  Success = 1,
}

export enum ApiRoutePrefix {
  ApiV1 = "/api/v1",
}

export enum ApiFieldKey {
  LanguageId = "language_id",
  LoginId = "login_id",
}

export enum ApiDefaultMessage {
  RequestFailed = "Request failed.",
  Unauthorized = "Unauthorized",
  UnexpectedClientError = "Unexpected API client error.",
}

export enum AuthStorageKey {
  SessionToken = "hrms_session_token",
  UserId = "hrms_user_id",
  TenantId = "hrms_tenant_id",
  CompanyId = "hrms_company_id",
  LanguageId = "hrms_language_id",
  SecondaryLanguageId = "hrms_secondary_language_id",
}

export enum AuthStoragePrefix {
  Hrms = "hrms_",
}

export enum DefaultContextValue {
  PrimaryId = "1",
}

export enum LoginUiMessage {
  UnableToSignIn = "Unable to sign in.",
  UnableToResendOtp = "Unable to resend OTP.",
}

export enum AlertDialogText {
  SuccessTitle = "Success",
  ErrorTitle = "Error",
  OkButton = "OK",
}

export enum UiKeyboardKey {
  Enter = "Enter",
}

export enum MasterApiResource {
  Translate = "/masters/translate",
  Departments = "/masters/departments",
  Designations = "/masters/designations",
  Banks = "/masters/banks",
  EssDeclarationCategories = "/masters/ess-declaration-categories",
  CostCenters = "/masters/cost-centers",
  Grades = "/masters/grades",
  Locations = "/masters/locations",
  Users = "/masters/users",
  Countries = "/masters/countries",
  States = "/masters/states",
  Employee = "/masters/employee",
  Family = "/masters/family",
  SalaryComponents = "/masters/salary-components",
  SalaryComponentFormOptions = "/masters/salary-component-form-options",
  PayrollCycles = "/masters/payroll-cycles",
  PayrollProcessLogs = "/masters/payroll-process-logs",
  VersionLogs = "/masters/version-logs",
  TaxRegimes = "/masters/tax-regimes",
  SalaryStructures = "/masters/salary-structures",
  EmployeeSalary = "/employee-salary",
}

export enum MasterApiRouteSegment {
  Detail = "detail",
  FormOptions = "form-options",
  Translate = "translate",
  BulkStatus = "bulk-status",
  BulkDelete = "bulk-delete",
  Status = "status",
  Address = "address",
  Bank = "bank",
  Statutory = "statutory",
  Experiences = "experiences",
  Qualifications = "qualifications",
  Family = "family",
  Slabs = "slabs",
  Clone = "clone",
  Summary = "summary",
  Revisions = "revisions",
  Unassign = "unassign",
}

export enum MasterMenuAction {
  DepartmentList = "MASTER_DEPARTMENT_LIST",
  DepartmentCreate = "MASTER_DEPARTMENT_CREATE",
  DepartmentUpdate = "MASTER_DEPARTMENT_UPDATE",
  DepartmentBulkStatus = "MASTER_DEPARTMENT_BULK_STATUS",
  DepartmentBulkDelete = "MASTER_DEPARTMENT_BULK_DELETE",
  DesignationList = "MASTER_DESIGNATION_LIST",
  DesignationCreate = "MASTER_DESIGNATION_CREATE",
  DesignationUpdate = "MASTER_DESIGNATION_UPDATE",
  DesignationBulkStatus = "MASTER_DESIGNATION_BULK_STATUS",
  DesignationBulkDelete = "MASTER_DESIGNATION_BULK_DELETE",
  BankList = "MASTER_BANK_LIST",
  BankCreate = "MASTER_BANK_CREATE",
  BankUpdate = "MASTER_BANK_UPDATE",
  BankBulkStatus = "MASTER_BANK_BULK_STATUS",
  BankBulkDelete = "MASTER_BANK_BULK_DELETE",
  EssDeclarationCategoryList = "MASTER_ESS_DECLARATION_CATEGORY_LIST",
  EssDeclarationCategoryCreate = "MASTER_ESS_DECLARATION_CATEGORY_CREATE",
  EssDeclarationCategoryUpdate = "MASTER_ESS_DECLARATION_CATEGORY_UPDATE",
  EssDeclarationCategoryBulkStatus = "MASTER_ESS_DECLARATION_CATEGORY_BULK_STATUS",
  EssDeclarationCategoryBulkDelete = "MASTER_ESS_DECLARATION_CATEGORY_BULK_DELETE",
  CostCenterList = "MASTER_COST_CENTER_LIST",
  CostCenterCreate = "MASTER_COST_CENTER_CREATE",
  CostCenterUpdate = "MASTER_COST_CENTER_UPDATE",
  CostCenterBulkStatus = "MASTER_COST_CENTER_BULK_STATUS",
  CostCenterBulkDelete = "MASTER_COST_CENTER_BULK_DELETE",
  GradeList = "MASTER_GRADE_LIST",
  GradeCreate = "MASTER_GRADE_CREATE",
  GradeUpdate = "MASTER_GRADE_UPDATE",
  GradeBulkStatus = "MASTER_GRADE_BULK_STATUS",
  GradeBulkDelete = "MASTER_GRADE_BULK_DELETE",
  LocationList = "MASTER_LOCATION_LIST",
  LocationFormOptions = "MASTER_LOCATION_FORM_OPTIONS",
  LocationCreate = "MASTER_LOCATION_CREATE",
  LocationUpdate = "MASTER_LOCATION_UPDATE",
  LocationBulkStatus = "MASTER_LOCATION_BULK_STATUS",
  LocationBulkDelete = "MASTER_LOCATION_BULK_DELETE",
  UserList = "MASTER_USER_LIST",
  UserFormOptions = "MASTER_USER_FORM_OPTIONS",
  UserCreate = "MASTER_USER_CREATE",
  UserUpdate = "MASTER_USER_UPDATE",
  UserBulkStatus = "MASTER_USER_BULK_STATUS",
  UserBulkDelete = "MASTER_USER_BULK_DELETE",
  CountryList = "MASTER_COUNTRY_LIST",
  CountryCreate = "MASTER_COUNTRY_CREATE",
  CountryUpdate = "MASTER_COUNTRY_UPDATE",
  CountryBulkStatus = "MASTER_COUNTRY_BULK_STATUS",
  CountryBulkDelete = "MASTER_COUNTRY_BULK_DELETE",
  StateList = "MASTER_STATE_LIST",
  StateCreate = "MASTER_STATE_CREATE",
  StateUpdate = "MASTER_STATE_UPDATE",
  StateBulkStatus = "MASTER_STATE_BULK_STATUS",
  StateBulkDelete = "MASTER_STATE_BULK_DELETE",
  EmployeeList = "MASTER_EMPLOYEE_LIST",
  EmployeeFormOptions = "MASTER_EMPLOYEE_FORM_OPTIONS",
  EmployeeView = "MASTER_EMPLOYEE_VIEW",
  EmployeeCreate = "MASTER_EMPLOYEE_CREATE",
  EmployeeUpdate = "MASTER_EMPLOYEE_UPDATE",
  EmployeeBulkStatus = "MASTER_EMPLOYEE_BULK_STATUS",
  EmployeeBulkDelete = "MASTER_EMPLOYEE_BULK_DELETE",
  EmployeeAddressView = "MASTER_EMPLOYEE_ADDRESS_VIEW",
  EmployeeAddressSave = "MASTER_EMPLOYEE_ADDRESS_SAVE",
  EmployeeBankView = "MASTER_EMPLOYEE_BANK_VIEW",
  EmployeeBankSave = "MASTER_EMPLOYEE_BANK_SAVE",
  EmployeeStatutoryView = "MASTER_EMPLOYEE_STATUTORY_VIEW",
  EmployeeStatutorySave = "MASTER_EMPLOYEE_STATUTORY_SAVE",
  EmployeeExperienceList = "MASTER_EMPLOYEE_EXPERIENCE_LIST",
  EmployeeExperienceSave = "MASTER_EMPLOYEE_EXPERIENCE_SAVE",
  EmployeeExperienceDelete = "MASTER_EMPLOYEE_EXPERIENCE_DELETE",
  EmployeeQualificationList = "MASTER_EMPLOYEE_QUALIFICATION_LIST",
  EmployeeQualificationSave = "MASTER_EMPLOYEE_QUALIFICATION_SAVE",
  EmployeeQualificationDelete = "MASTER_EMPLOYEE_QUALIFICATION_DELETE",
  EmployeeFamilyList = "MASTER_EMPLOYEE_FAMILY_LIST",
  EmployeeFamilySave = "MASTER_EMPLOYEE_FAMILY_SAVE",
  EmployeeFamilyDelete = "MASTER_EMPLOYEE_FAMILY_DELETE",
  SalaryComponentList = "MASTER_SALARY_COMPONENT_LIST",
  SalaryComponentGet = "MASTER_SALARY_COMPONENT_GET",
  SalaryComponentFormOptions = "MASTER_SALARY_COMPONENT_FORM_OPTIONS",
  SalaryComponentCreate = "MASTER_SALARY_COMPONENT_CREATE",
  SalaryComponentUpdate = "MASTER_SALARY_COMPONENT_UPDATE",
  SalaryComponentStatus = "MASTER_SALARY_COMPONENT_STATUS",
  SalaryComponentDelete = "MASTER_SALARY_COMPONENT_DELETE",
  PayrollCycleList = "MASTER_PAYROLL_CYCLE_LIST",
  PayrollCycleGet = "MASTER_PAYROLL_CYCLE_GET",
  PayrollCycleFormOptions = "MASTER_PAYROLL_CYCLE_FORM_OPTIONS",
  PayrollCycleCreate = "MASTER_PAYROLL_CYCLE_CREATE",
  PayrollCycleUpdate = "MASTER_PAYROLL_CYCLE_UPDATE",
  PayrollCycleStatus = "MASTER_PAYROLL_CYCLE_STATUS",
  PayrollProcessLogList = "MASTER_PAYROLL_PROCESS_LOG_LIST",
  PayrollProcessLogFormOptions = "MASTER_PAYROLL_PROCESS_LOG_FORM_OPTIONS",
  VersionLogList = "MASTER_VERSION_LOG_LIST",
  VersionLogGet = "MASTER_VERSION_LOG_GET",
  VersionLogCreate = "MASTER_VERSION_LOG_CREATE",
  VersionLogUpdate = "MASTER_VERSION_LOG_UPDATE",
  VersionLogStatus = "MASTER_VERSION_LOG_STATUS",
  TaxRegimeList = "MASTER_TAX_REGIME_LIST",
  TaxRegimeGet = "MASTER_TAX_REGIME_GET",
  TaxRegimeFormOptions = "MASTER_TAX_REGIME_FORM_OPTIONS",
  TaxRegimeCreate = "MASTER_TAX_REGIME_CREATE",
  TaxRegimeUpdate = "MASTER_TAX_REGIME_UPDATE",
  TaxRegimeStatus = "MASTER_TAX_REGIME_STATUS",
  TaxSlabList = "MASTER_TAX_SLAB_LIST",
  TaxSlabSave = "MASTER_TAX_SLAB_SAVE",
  SalaryStructureList = "MASTER_SALARY_STRUCTURE_LIST",
  SalaryStructureGet = "MASTER_SALARY_STRUCTURE_GET",
  SalaryStructureFormOptions = "MASTER_SALARY_STRUCTURE_FORM_OPTIONS",
  SalaryStructureCreate = "MASTER_SALARY_STRUCTURE_CREATE",
  SalaryStructureUpdate = "MASTER_SALARY_STRUCTURE_UPDATE",
  SalaryStructureClone = "MASTER_SALARY_STRUCTURE_CLONE",
  SalaryStructureStatus = "MASTER_SALARY_STRUCTURE_STATUS",
  SalaryStructureDelete = "MASTER_SALARY_STRUCTURE_DELETE",
  EmployeeSalaryList = "EMPLOYEE_SALARY_LIST",
  EmployeeSalaryFormOptions = "EMPLOYEE_SALARY_FORM_OPTIONS",
  EmployeeSalaryView = "EMPLOYEE_SALARY_VIEW",
  EmployeeSalarySummary = "EMPLOYEE_SALARY_SUMMARY",
  EmployeeSalarySave = "EMPLOYEE_SALARY_SAVE",
}
